import openpyxl, sys, json

liquorIssued = sys.argv[1]
liquorReturned = sys.argv[2]
beerIssued = sys.argv[3]
beerReturned = sys.argv[4]
wineIssued = sys.argv[4]
wineReturned = sys.argv[5]
eventInfo = sys.argv[6]
liquorPricing = sys.argv[7]
winePricing = sys.argv[8]
beerPricing = sys.argv[9]

psDataJson = json.loads(f)
wb = openpyxl.load_workbook('GCC Point Sheet Template 2015.06.19.xlsx')
inputSheet = wb.get_sheet_by_name('Input')
pointSheet = wb.get_sheet_by_name('Point')

inputSheet['C5'] ['eventNumber']
inputSheet['C6'] ['eventDate']
inputSheet['C7'] ['bartenders']
inputSheet['C8'] ['room']
inputSheet['C9'] ['hostbar']
inputSheet['C10'] ['salesTax']
inputSheet['C11'] ['ServiceCharge']
inputSheet['C12'] ['CashCollected']
inputSheet['C15'] ['callLiquorPrice']
inputSheet['C16'] ['premiumLiquorPrice']
inputSheet['C17'] ['topLiquorPrice']
inputSheet['C18'] ['wellLiquorPrice']
inputSheet['C22'] ['chardonnayPrice']
inputSheet['C23'] ['merlotPrice']
inputSheet['C24'] ['cabernetSauvignonPrice']
inputSheet['C25'] ['pinotGrigioPrice']
inputSheet['C26'] ['whiteZinfandel']
inputSheet['C27'] ['champagnePrice']
inputSheet['C29'] ['domesticBeerPrice']
inputSheet['C30'] ['importBeerPrice']

pointSheet['e6'] ['AristocratVodkaIssued']
pointSheet['e7'] ['SmirnoffIssued']
pointSheet['e8'] ['AbsolutIssued']
pointSheet['e9'] ['CirocIssued']
pointSheet['e10'] ['Aristocrat RumIssued']
pointSheet['e11'] ['BacardiIssued']
pointSheet['e12'] ['Captain Morgan']
pointSheet['e13'] ['Aristocrat Gin']
pointSheet['e14'] ['Gordons']
pointSheet['e15'] ['Tanqueray']
pointSheet['e16'] ['Aristocrat Tequila']
pointSheet['e17'] ['Jose Cuervo GoldIssued']
pointSheet['e18'] ['PatronIssued']
pointSheet['e19'] ['DewarsIssued']
pointSheet['e20'] ['HennessyIssued']
pointSheet['e21'] ['JimBeamIssued']
pointSheet['e22'] ['Jack DanielsIssued']
pointSheet['e23'] ['Seagrams 7Issued']
pointSheet['e24'] ['Crown RoyalIssued']
pointSheet['e25'] ['AmarettoIssued']
pointSheet['e26'] ['Blue CuracoIssued']
pointSheet['e27'] ['Peach SchnappsIssued']
pointSheet['e28'] ['Triple SecIssued']
pointSheet['e29'] ['FireballIssued']
pointSheet['e30'] ['Johnnie Walker BlackIssued']
pointSheet['e31'] ['JamesonIssued']
pointSheet['e32'] ['GreyGooseIssued']

pointSheet['f6'] ['AristocratVodkaReturned']
pointSheet['f7'] ['SmirnoffReturned']
pointSheet['f8'] ['AbsolutReturned']
pointSheet['f9'] ['CirocReturned']
pointSheet['f10'] ['Aristocrat RumReturned']
pointSheet['f11'] ['BacardiReturned']
pointSheet['f12'] ['Captain MorganReturned']
pointSheet['f13'] ['Aristocrat GinReturned']
pointSheet['f14'] ['GordonsReturned']
pointSheet['f15'] ['TanquerayReturned']
pointSheet['f16'] ['Aristocrat TequilaReturned']
pointSheet['f17'] ['Jose Cuervo GoldReturned']
pointSheet['f18'] ['PatronReturned']
pointSheet['f19'] ['DewarsReturned']
pointSheet['f20'] ['HennessyReturned']
pointSheet['f21'] ['JimBeamReturned']
pointSheet['f22'] ['Jack DanielsReturned']
pointSheet['f23'] ['Seagrams 7Returned']
pointSheet['f24'] ['Crown RoyalReturned']
pointSheet['f25'] ['AmarettoReturned']
pointSheet['f26'] ['Blue CuracoReturned']
pointSheet['f27'] ['Peach SchnappsReturned']
pointSheet['f28'] ['Triple SecReturned']
pointSheet['f29'] ['FireballReturned']
pointSheet['f30'] ['Johnnie Walker BlackReturned']
pointSheet['f31'] ['JamesonReturned']
pointSheet['f32'] ['GreyGooseReturned']

pointSheet['e40'] ['BudLightIssued']
pointSheet['e41'] ['BudLightPlatinumIssued']
pointSheet['e42'] ['BudLightLimeIssued']
pointSheet['e43'] ['BudweiserIssued']
pointSheet['e44'] ['CoorsLightIssued']
pointSheet['e45'] ['CoronaIssued']
pointSheet['e46'] ['HeinekenIssued']
pointSheet['e47'] ['MichelobUltraIssued']
pointSheet['e48'] ['MillerLiteIssued']
pointSheet['e49'] ['NaturalLightIssued']
pointSheet['e50'] ['YuenglingIssued']

pointSheet['f40'] ['BudLightReturned']
pointSheet['f41'] ['BudLightPlatinumReturned']
pointSheet['f42'] ['BudLightLimeReturned']
pointSheet['f43'] ['BudweiserReturned']
pointSheet['f44'] ['CoorsLightReturned']
pointSheet['f45'] ['CoronaReturned']
pointSheet['f46'] ['HeinekenReturned']
pointSheet['f47'] ['MichelobUltraReturned']
pointSheet['f48'] ['MillerLiteReturned']
pointSheet['f49'] ['NaturalLightReturned']
pointSheet['f50'] ['YuenglingReturned']

pointSheet['e58'] ['ChardonnayIssued']
pointSheet['e59'] ['MerlotIssued']
pointSheet['e60'] ['CabernetSauvignonIssued']
pointSheet['e61'] ['PinotGrigioIssued']
pointSheet['e62'] ['WhiteZinfandelIssued']
pointSheet['e63'] ['ChampagneIssued']

pointSheet['f58'] ['ChardonnayReturned']
pointSheet['f59'] ['MerlotReturned']
pointSheet['f60'] ['CabernetSauvignonReturned']
pointSheet['f61'] ['PinotGrigioReturned']
pointSheet['f62'] ['WhiteZinfandelReturned']
pointSheet['f63'] ['ChampagneReturned']

# TODO
# Designate which cells each piece of data is assigned to
# Write Data to workbook object
# Establish smtp functionality
# Attach new point sheet as attachment to email object
