export const default_info = {
  "Event Number": "",
  "Event Date": "",
  "Bartenders": "",
  "Room": "",
  "Host": "n",
  "Sales Tax": "7%",
  "Service Charge": "21%",
  "Cash Collected": "$0.00",
  "Call Liquor Price": "$6.00",
  "Premium Liquor Price": "$7.00",
  "Top Liquor Price": "$9.00",
  "Well Liquor Price": "$5.00",
  "Chardonnay Price": "$5.00",
  "Merlot Price": "$5.00",
  "Cabernet Sauvignon Price": "$5.00",
  "Pinot Grigio Price": "$5.00",
  "White Zinfandel Price": "$5.00",
  "Champagne Price": "$5.00",
  "Domestic Beer Price": "$4.00",
  "Import Beer Price": "$5.00"
};
