export const default_info = {
  eventNumber: "",
  eventDate: "",
  bartenders: "",
  room: "",
  host: "n",
  salesTax: "7%",
  serviceCharge: "21%",
  cashCollected: "$1400.00",
  callLiquorPrice: "$6.00",
  premiumLiquorPrice: "$7.00",
  topLiquorPrice: "$9.00",
  wellLiquorPrice: "$5.00",
  chardonnayPrice: "$5.00",
  merlotPrice: "$5.00",
  cabernetSauvignonPrice: "$5.00",
  pinotGrigioPrice: "$5.00",
  whiteZinfandelPrice: "$5.00",
  champagnePrice: "$5.00",
  domesticBeerPrice: "$4.00",
  importBeerPrice: "$5.00"
};
